
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r demo/test_requirements.txt
  - pip install coveralls
  - python setup.py develop
script:
  - cd demo
  - coverage run --source='../djfiles' manage.py test djfiles
after_success:
  - coveralls