# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='MIME type')),
                ('content', models.FileField(upload_to=b'files/', verbose_name='\u041a\u043e\u043d\u0442\u0435\u043d\u0442')),
            ],
            options={
                'db_table': 'files',
                'verbose_name': '\u0444\u0430\u0439\u043b',
                'verbose_name_plural': '\u0444\u0430\u0439\u043b\u044b',
            },
        ),
    ]
