# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import jinx_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('jinx_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to=jinx_files.models.file_upload_to),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
