# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinx_files', '0002_auto_20160226_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
